---
- name: Common configuration
  hosts: all
  roles:
    - common

- name: Configure Jellyfin
  hosts: jellyfin
  roles:
    - jellyfin

- name: Configure Docker
  hosts: docker
  roles:
    - common
    - docker
    - arr 

